server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:aviation;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: warn